// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tynnedxpecphluxeaxqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bm5lZHhwZWNwaGx1eGVheHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDU4ODgsImV4cCI6MjA3MjM4MTg4OH0.7t48TLBryL-bEa3rdy5vlzYjJNHj47j0RX6jv5gqqHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});